# Generated by Django 6.0.3 on 2026-04-03 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetaInvestimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_nome', models.CharField(max_length=100)),
                ('valor_alvo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prazo', models.CharField(choices=[('CURTO', 'Curto Prazo'), ('LONGO', 'Longo Prazo')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Planejamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('GASTO FIXO', 'Gasto Fixo'), ('LAZER', 'Lazer'), ('ESTUDO', 'Estudo'), ('INVESTIMENTO', 'Investimento'), ('SAUDE', 'Saude')], max_length=20, unique=True)),
                ('valor_limite', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('GASTO FIXO', 'Gasto Fixo'), ('LAZER', 'Lazer'), ('ESTUDO', 'Estudo'), ('INVESTIMENTO', 'Investimento'), ('SAUDE', 'Saude')], max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao', models.CharField(max_length=200)),
                ('data', models.DateField()),
                ('meta_relacionada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aportes', to='records.metainvestimento')),
            ],
        ),
    ]
