# Generated by Django 6.0.3 on 2026-04-04 00:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
