# Generated by Django 6.0.3 on 2026-04-04 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_alter_gasto_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metainvestimento',
            name='prazo',
            field=models.CharField(choices=[('CURTO', 'Curto Prazo'), ('MEDIO', 'Medio Prazo'), ('LONGO', 'Longo Prazo')], max_length=10),
        ),
    ]
