# Generated by Django 6.0.3 on 2026-04-04 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_alter_metainvestimento_prazo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fixos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fluxo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saida')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Parcela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo', models.CharField(choices=[('GASTO FIXO', 'Gasto Fixo'), ('LAZER', 'Lazer'), ('ESTUDO', 'Estudo'), ('INVESTIMENTO', 'Investimento'), ('SAUDE', 'Saude')], max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Planejamento',
        ),
    ]
