# Generated by Django 6.0.3 on 2026-04-04 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_fixos_parcela_delete_planejamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='tipo',
            field=models.CharField(choices=[('LAZER', 'Lazer'), ('ESTUDO', 'Estudo'), ('INVESTIMENTO', 'Investimento'), ('SAUDE', 'Saude')], max_length=20),
        ),
        migrations.AlterField(
            model_name='parcela',
            name='tipo',
            field=models.CharField(choices=[('LAZER', 'Lazer'), ('ESTUDO', 'Estudo'), ('INVESTIMENTO', 'Investimento'), ('SAUDE', 'Saude')], max_length=20),
        ),
    ]
