# Generated by Django 6.0.3 on 2026-04-04 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_alter_gasto_tipo_alter_parcela_tipo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fixos',
            new_name='Fixo',
        ),
    ]
