# Generated by Django 6.0.3 on 2026-04-04 19:35

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0006_rename_fixos_fixo'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcela',
            name='nome',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='parcela',
            name='vezes',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='fixo',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='metainvestimento',
            name='valor_alvo',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='parcela',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
