# Generated by Django 6.0.3 on 2026-04-04 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0007_parcela_nome_parcela_vezes_alter_fixo_valor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parcela',
            old_name='vezes',
            new_name='parcelas_totais',
        ),
        migrations.AddField(
            model_name='parcela',
            name='parcelas_pagas',
            field=models.IntegerField(default=1),
        ),
    ]
