# Generated by Django 6.0.3 on 2026-04-04 20:34

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0008_rename_vezes_parcela_parcelas_totais_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planejamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('LAZER', 'Lazer'), ('ESTUDO', 'Estudo'), ('INVESTIMENTO', 'Investimento'), ('SAUDE', 'Saude')], unique=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
            ],
        ),
    ]
